### PR TITLE
python3 support

### PR DESCRIPTION
**Pull request by schlichtanders**
[ This should solve #2 ]

Dear Oliver Tonnhofer, thank you very much for your awesome little package

I adapted your code to also include python3 support. I tested your tests using pytest and got rid everything but the following error:

```python
Failure
Traceback (most recent call last):
  File "D:\Projects\scriptine\test\test_path.py", line 319, in testShutil
    stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR | stat.S_IRGRP)
AssertionError: False is not true
```
I am not sure why this happens..

Further I tried your first example in the README and found some other errors.
I haven't tested it on python2.7 or something earlier, however all changes are compatible to the best of my knowledge.

I hope, that python3 will be soon integrated into scriptine =)
all the best,
Stephan

One last note: You build your own path object, that seems pretty awesome. You may know that there is pathlib (for python3) and pathlib2 (for python2) which do a very similar thing, however belong to the standard library since python 3.5 or something like that. They unfortunately miss your dry_run option, however still it might be fruitful to extend the new pathlib with your features at some time.

### CODE REVIEW

**Comment by schlichtanders** [comment]
also note that I replaced your decorator functionality with ``wrapt.decorator`` because it just constantly broke with my python3

Hence you now have the dependency on ``wrapt``, however wrapt is already a stable package and I would definitely recommend it for function decorators.

I think this is the best solution to the previous python3 incompatible decorator

**Review by YonatanKiron — APPROVED** [review]

**Comment by bouke-nederstigt** [comment]
+1 please merge this pull request / publish new package. Would love to be able to use scriptine with python 3

**Comment by elgow** [comment]
+1 Scriptine looks very useful but Python 3 support is becoming necessary to remain relevant in the Python world.  Please merge this PR.

**Comment by tdonovic** [comment]
This is still an issue in 2019, and means I am struggling to install my dependencies for my project, because this is a dep somewhere along the line. Please merge this PR

**Comment by olt** [comment]
I'm no longer using scriptine and I don't intend to make another release.
I recommend to use something else, or make a fork.

**Pull request closed without merging**
